# **Módulo 1: Fundamentos de Python para análisis de datos**

**Variables**

Las __variables__ son nombres que hacen referencia a un valor. Este valor puede cambiar a lo largo de la ejecución de un programa. Las __variables__ son espacios de la memoria principal del computador, en donde se almacenan valores de forma temporal o permanente durante la ejecución de un programa.

*   __Operacción de asignación__: Para darles el valor a las variables, se realiza la operación de asignación. Esta se hace mediante el signo igual (=), escrito entre el nombre de la variable y el elemento que se le asigna. El elemento asignado puede ser un valor, otra variable previamente definida o una expresión resultante del uso de otras variables, valores u operadores. Algunos ejemplos de asignación son:

In [ ]:
# Creando obejtos y asignando valores a variables
a = 3
b = 5
d = a
c = a+b

In [8]:
print(a)

3

### **1.3.3 Sentencias**

In [10]:
# Uso de la función básica input
input("Escribe algo: ")

'26'

In [11]:
# Uso de la función input con prompt
x = input('Escribe un número real: ')

In [ ]:
# tipo de dato de x
type(x)

str

In [15]:
# Conversión de una string numérico entero a un entero
x = int(input('Escribe un número real: '))
type(x)

int

In [19]:
# Conversión de una string numérico decimal a un número decimal
x = float(input('Escribe un número real: '))
type(x)

float

*   **Sentencia de salida**: La sentencia de salida de datos corresponden a la función `print`. Esta sentencia se utiliza para mostrar texto y otros tipos de datos en la consola. Por ejemplo

In [24]:
# Uso del print
print("Python")

# Uso de la función básica print
print('El número ingresado es:', x)

# Uso del print con varias palabras sin separarla
print('Ciencia' 'de' 'Datos')

# Uso del print con varias palabras con separación
print('Ciencia', 'de', 'Datos')

Python
El número ingresado es: 3.0
CienciadeDatos
Ciencia de Datos

In [26]:
# Uso del print con espacio sin salto de linea
# end = ' ', tiene un espacio
print('Ciencia', end = ' ')
print('de', end = ' ')
print('datos')

Ciencia de datos

In [27]:
# Uso del print con salto de línea
print('Ciencia' '\n' 'de' '\n' 'datos')

Ciencia
de
datos

In [28]:
# Otra forma de salto de linea
# end = '\n'
print('Ciencia', end = '\n')
print('de', end = '\n')
print('datos')

Ciencia
de
datos

In [29]:
# Uso de print separado por un caracter
print('Ciencia','de','datos',sep='\\')

Ciencia\de\datos

### **1.3.4 Operaciones aritmeticas**

In [32]:
# Uso de las operaciones aritmeticas
# Definición de variables
a = 5
b = 3
c = 2

# Combinación de varios operadores aritméticos en una sola línea
resultado = ((a + b) * c) - (a / b) ** c % b // c
print(f'Resultado: (({a} + {b}) * {c}) - ({a} / {b}) ** {c} % {b} // {c} = {resultado}')

Resultado: ((5 + 3) * 2) - (5 / 3) ** 2 % 3 // 2 = 15.0

**Observación**: La concatenación de caracteres en Python se realiza utilizando el operador `+`. Este operador permite unir dos o más cadenas de texto en una sola cadena. Es importante asegurarse de que ambos operandos sean cadenas de texto para evitar errores de tipo. Aquí tienes un ejemplo:

In [34]:
cadena1 = 'Hola'
cadena2 = '¿Cómo estás?'
cadena1 +' '+ cadena2

'Hola ¿Cómo estás?'

### **1.3.5 Símbolos de asignación aumentada**

In [35]:
# uso de la asignación aumentada
# definamos las variables
a=3; b=2

# asignación aumenta
a += 2
b *= 3

# imprimir las nuevas asignaciones
print(f'El valor de a es {a}, el valor de b es {b}')

El valor de a es 5, el valor de b es 6

### **1.3.6 Operadores de comparación**

In [ ]:
# Uso de las operaciones de comparación
# Definicion de variables
a = # tu codigo aquí
b = # tu codigo aquí
print(# tu codigo aquí)
print(# tu codigo aquí)

### **1.3.7 Operadores lógicos**:

In [ ]:
# Operadores lógicos
print(# tu codigo aquí)
print(# tu codigo aquí)

### **1.3.8 Estructuras algorítmicas**

#### **1.3.8.1 Sentencias condicionales**

Las __sentencias condicionales__ son estructuras de programación que permiten ejecutar cierto bloque de código si se cumple una condición especificada. En las sentencias condicionales, siempre habrá una condición después de la palabra clave.



*   **Sentencia if-else simple**: Las sentencias __if-else__ en programación permiten tomar decisiones dentro de un algoritmo. La estructura básica es la siguiente:

```python
if condición:
    bloque de código a ejecutar si la condición es verdadera
else:
    bloque de código a ejecutar si la condición es falsa
```

El flujo de control funciona así: primero, se evalúa la condición. Si la condición es verdadera (`True`), se ejecuta el bloque de código dentro del `if`. Si la condición es falsa (`False`), se ejecuta el bloque de código dentro del else. Por ejemplo:

In [ ]:
# Definición de la variable
edad = # tu codigo aquí

# sentencia if-else
if # tu codigo aquí:
    print(# tu codigo aquí)
else:
    print(# tu codigo aquí)

*   **Sentencia if-else anidada**: Las sentencias __if-else anidadas__ permiten manejar múltiples condiciones en un algoritmo, ejecutando diferentes bloques de código según diversas situaciones. La estructura básica de una sentencia `if-else` anidada es la siguiente:

```python
if condición1:
     bloque de código a ejecutar si condición1 es verdadera
    if condición1_1:
        bloque de código a ejecutar si condición1_1 es verdadera
    else:
        bloque de código a ejecutar si condición1_1 es falsa
else:
    if condición2:
        bloque de código a ejecutar si condición2 es verdadera
    else:
        bloque de código a ejecutar si condición2 es falsa
```

Cada `if` o `else` dentro de otro `if` o `else` se denomina __anidado__. Esta estructura permite evaluar múltiples condiciones de manera secuencial. Por ejemplo

In [ ]:
# definición de la variable
nota = float(input('Escriba la nota que obtuvo en el examen '))

# sentencia if-else anidada
if # tu codigo aquí:
    print("Excelente")
else:
    if # tu codigo aquí:
        print("Muy bien")
    else:
        if # tu codigo aquí:
            print("Bien")
        else:
            print("Necesita mejorar")

*   **Sentencia if-elif anidada**

La sentencia __if-elif__ en programación es una forma abreviada de manejar múltiples condiciones consecutivas sin necesidad de anidar múltiples `else-if`. La palabra clave __elif__ (abreviatura de `else if`) permite evaluar una nueva condición si la condición anterior es falsa, simplificando la estructura del código y mejorando su legibilidad. La estructura básica de una sentencia `if-elif` es la siguiente:

```python
if condición1:
    bloque de código a ejecutar si condición1 es verdadera
elif condición2:
    bloque de código a ejecutar si condición2 es verdadera
elif condición3:
    bloque de código a ejecutar si condición3 es verdadera
else:
    bloque de código a ejecutar si ninguna de las condiciones anteriores es verdadera
```

Cada `elif` es evaluado solo si las condiciones anteriores son falsas. Si una condición `elif` es verdadera, su bloque de código correspondiente se ejecuta y las demás condiciones no se evalúan. Por ejemplo

In [ ]:
# definición de la variable
nota = float(input('Escriba la nota que obtuvo en el examen '))

# sentencia elif anidada
if # tu codigo aquí:
    print("Excelente")
elif # tu codigo aquí:
    print("Muy bien")
elif # tu codigo aquí:
    print("Bien")
else:
    print("Necesita mejorar")

#### **1.3.8.2 Sentencias repetitivas**

Las __sentencias repetitivas__, también conocidas como __bucles__ o __ciclos__, son estructuras de programación que permiten ejecutar repetidamente un bloque de código mientras se cumple una condición específica o durante un número determinado de iteraciones. Estas sentencias son esenciales para automatizar tareas repetitivas y para procesar secuencias de datos de manera eficiente. Los tipos más comunes de sentencias repetitivas incluyen:

*  **Bucle For**: El bucle `for` es una estructura de control de flujo que permite iterar sobre una secuencia de elementos (como una lista, tupla, cadena, conjunto o rango) y ejecutar un bloque de código para cada elemento de la secuencia. Este tipo de bucle es muy útil cuando se sabe de antemano cuántas veces se debe repetir el bloque de código, o cuando se quiere realizar una operación en cada elemento de una colección. La estructura básica de un bucle for en Python es:

```python
for elemento in secuencia:
    bloque de código a ejecutar para cada elemento
```

Aquí, elemento es una variable que toma el valor de cada elemento en la secuencia durante cada iteración del bucle. El bloque de código dentro del bucle se ejecuta una vez por cada elemento en la secuencia. Por ejemplo

In [ ]:
# Definicion de variable
palabra = # tu codigo aquí

# Iterar sobre una cadena
for # tu codigo aquí:
    print(# tu codigo aquí)

In [ ]:
# Iterar sobre un rango de números
for # tu codigo aquí:
    print(# tu codigo aquí)

In [ ]:
# Definicion de variable
frutas = # tu codigo aquí

# Iterar sobre una lista
for # tu codigo aquí:
    print(# tu codigo aquí)

Dentro de un bucle `for`, se pueden usar las declaraciones __break__ y __continue__ para controlar el flujo del bucle:

*   **break**: Termina el bucle prematuramente, es decir, sale del bucle cuando se cumple una condición específica.
*   **continue**: Salta a la siguiente iteración del bucle, omitiendo el resto del bloque de código para la iteración actual.

In [ ]:
# definición de variables
numeros = [1, 2, 3, 4, 5]

# uso del break
for numero in numeros:
    if numero == 3:
        break  # Sale del bucle cuando numero es 3
    print(numero)

# uso del continue
for numero in numeros:
    if numero % 2 == 0:
        continue  # Salta a la siguiente iteración cuando numero es par
    print(numero)

*   __Bucle While__: El bucle __while__ son estructuras de control de flujo que permiten ejecutar repetidamente un bloque de código mientras se cumpla una condición específica. La estructura básica de un bucle while es la siguiente:

```python
while condición:
    bloque de código a ejecutar mientras la condición sea verdadera
```

El flujo de control funciona de la siguiente manera: primero, se evalúa la condición. Si la condición es verdadera (`True`), se ejecuta el bloque de código dentro del `while`. Después de ejecutar el bloque de código, se vuelve a evaluar la condición. Este proceso se repite hasta que la condición se vuelve falsa (`False`). Por ejemplo en Python:

In [ ]:
# definición de variable
i = 0

# iteración con el bucle while
while # tu codigo aquí:
    print(# tu codigo aquí)
    # tu codigo aquí

Tambíen, dentro de un bucle `while`, se pueden usar las declaraciones `break` y `continue` para controlar el flujo del bucle. Por ejemplo

In [ ]:
# definición de variable
i = 0

# uso del break
while i < 10:
    if i == 5:
        break  # Sale del bucle cuando i es 5
    print(i)
    i += 1

i = 0

# uso del continue
while i < 10:
    i += 1
    if i % 2 == 0:
        continue  # Salta a la siguiente iteración cuando i es par
    print(i)

### **1.3.9 Funciones en python**

Las funciones en Python son bloques de código diseñados para realizar tareas específicas y se pueden reutilizar en diferentes partes del programa. Definir y usar funciones te permite organizar tu código de manera más efectiva y reducir la redundancia.

1.   **Definición de una función**: Una __función__ se define utilizando la palabra clave `def`, seguida del nombre de la función y un paréntesis que puede contener parámetros. Dentro del bloque de código de la función, se especifican las instrucciones que se ejecutarán cuando se llame a la función.

```python
def nombre_de_la_funcion(nombre):
    """Esta función recibe un nombre (input) y muestra un saludo (output)."""
    cuerpo
    return respuesta
```

Por ejemplo

In [ ]:
def # tu codigo aquí:
    """Esta función recibe un nombre (input) y muestra un saludo (output)."""
    saludo = # tu codigo aquí
    return saludo

**Observación**: Las variables creadas dentro de una función son variables locales (son válidas dentro de la función donde se usan).

2.   **Llamada a la función**: Para ejecutar el código dentro de una función, se llama a la función por su nombre y se pasan los argumentos necesarios, si los hay.

In [ ]:
mensaje = # tu codigo aquí
print(mensaje)  # Salida: Hola, Ana!

3.   **Funciones con parámetros por defecto**: Las funciones pueden tener parámetros con valores predeterminados. Si el usuario no proporciona un argumento para ese parámetro, se utilizará el valor predeterminado.

In [ ]:
def saludar(nombre="Invitado"):
    """Esta función recibe un nombre y muestra un saludo.
     Si no se proporciona un nombre, usa 'Invitado'."""
    saludo = f"Hola, {nombre}!"
    return saludo

# Llamada a la función sin argumentos
mensaje1 = saludar()
print(mensaje1)  # Output: Hola, Invitado!

# Llamada a la función con un argumento
mensaje2 = saludar("Carlos")
print(mensaje2)  # Output: Hola, Carlos!

4.   **Funciones con múltiples parámetros**: Una función puede aceptar múltiples parámetros y realizar operaciones con ellos.

In [ ]:
def # tu codigo aquí:
    """Esta función suma dos números y devuelve el resultado."""
    resultado = # tu codigo aquí
    return resultado

# Llamada a la función
resultado_suma = # tu codigo aquí

print(resultado_suma)  # Output: 15000

5.   **Funciones Anónimas (Lambdas)**: En Python, las funciones pequeñas y sin nombre se pueden crear usando la palabra clave `lambda`. Estas funciones son útiles para operaciones simples.

In [ ]:
# Definición de una función lambda
suma = # tu codigo aquí

# Llamada a la función lambda
resultado = suma(3, 7)
print(resultado)  # Output: 10

6. **Funciones Recursivas**: Una función recursiva es aquella que se llama a sí misma para resolver un problema. Es importante definir una condición de parada para evitar una recursión infinita.

In [ ]:
def factorial(n):
    """Esta función calcula el factorial de un número de manera recursiva."""
    if n == 0:
        return 1
    else:
        return n * factorial(n - 1)

# Llamada a la función
resultado_factorial = factorial(5)
print(resultado_factorial)  # Output: 120

7.  **Funciones Internas**: Python incluye una serie de funciones integradas que facilitan tareas comunes. Estas funciones están disponibles por defecto y no requieren importación adicional. Algunas de estas funciones internas son `len()`, `max()`, `min()`, etc., se llaman directamente con su nombre y los argumentos necesarios entre paréntesis. Estas funciones están disponibles globalmente en Python y no pertenecen a un objeto específico. Aquí puedes encontrar más funciones internas de python. Aquí tienes un enlace a la documentación oficial de Python sobre funciones integradas [built-in functions](https://docs.python.org/3/library/functions.html).

## **1.4 Uso de estructuras de datos básicas (vectores, listas, matrices, diccionarios)**

### **1.4.1 Vectores**

In [ ]:
# Crear un vector
vector = [10, 20, 30, 40, 50]

# Acceder al primer elemento (índice 0)
print(# tu codigo aquí)  # Output: 10

# Acceder al tercer elemento (índice 2)
print(# tu codigo aquí)  # Output: 30

*   __Modificación de elementos__:

In [ ]:
# Crear un vector
vector = [10, 20, 30, 40, 50]

# Modificar el segundo elemento (índice 1)
# tu codigo aquí
print(vector)  # Output: [10, 25, 30, 40, 50]

*   **Suma, resta, multiplicación y división de vectores**:
En programación científica, estas operaciones a menudo se realizan utilizando bibliotecas como `NumPy` para una mayor eficiencia y facilidad. Por ejemplo:

In [ ]:
# importar biblioteca
import numpy as np

# Crear dos vectores (arrays de NumPy)
vector1 = # tu codigo aquí
vector2 = # tu codigo aquí

# Suma de vectores
suma = vector1 + vector2
print("Suma:", suma)  # Output: [5 7 9]

# Resta de vectores
resta = vector1 - vector2
print("Resta:", resta)  # Output: [-3 -3 -3]

# Multiplicación de vectores
multiplicacion = vector1 * vector2
print("Multiplicación:", multiplicacion)  # Output: [ 4 10 18]

# División de vectores
division = vector1 / vector2
print("División:", division)  # Output: [0.25 0.4  0.5 ]

*   **Agregar elementos a un vector**:

In [ ]:
# Crear un vector
vector = [10, 20, 30]

# Agregar un nuevo elemento al final del vector
# tu codigo aquí
print(vector)  # Output: [10, 20, 30, 40]

### **1.4.2 Listas**

Algunas operaciones comunes son:

* **Añadir elementos**:

In [ ]:
# crear lista
lista = [1, 2, 3]

# append(): Añade un solo elemento al final de la lista
# tu codigo aquí
print(lista)  # Output: [1, 2, 3, 4]

# extend(): Añade múltiples elementos al final de la lista
# tu codigo aquí
print(lista)  # Output: [1, 2, 3, 4, 5, 6]

* **Eliminar elementos**:

In [ ]:
# crear lista
lista = [1, 2, 3, 4]

# remove(): Elimina la primera aparición de un valor en la lista.
# tu codigo aquí
print(lista)  # Output: [1, 3, 4]

# pop(): Elimina y devuelve el elemento en el índice especificado (por defecto, el último)
# tu codigo aquí
print(elemento)  # Output: 4
print(lista)  # Output: [1, 2, 3]

elemento = # tu codigo aquí
print(elemento)  # Output: 2
print(lista)  # Output: [1, 3]

*   **Ordenar elementos**:

In [ ]:
# crear lista
lista = [4, 2, 3, 1]

# sort(): Ordena los elementos de la lista en su lugar.
# tu codigo aquí
print(lista)  # Output: [1, 2, 3, 4]

# sorted(): Devuelve una nueva lista ordenada sin modificar la original.
lista_ordenada = # tu codigo aquí
print(lista_ordenada)  # Output: [1, 2, 3, 4]

### **1.4.3 Generadores de valores y vectores aleatorios**

In [ ]:
import numpy as np
import random as rand

# Establecer semillas para reproducibilidad
np.random.seed(42)
rand.seed(42)

#### **1.4.3.2 Números aleatorios uniforme con NumPy**

La distribución uniforme genera números que tienen la misma probabilidad de ocurrir en un rango especificado.

In [ ]:
# Generar un número aleatorio entre 0 y 1
num_aleatorio = # tu codigo aquí
print("Número aleatorio entre 0 y 1:", num_aleatorio)

# Generar un vector de 5 números aleatorios entre 0 y 1
vector_aleatorio = # tu codigo aquí
print("\nVector de 5 números aleatorios:\n", vector_aleatorio)

# Generar números aleatorios en un rango específico (entre 10 y 20)
num_rango = # tu codigo aquí
print("\n5 números aleatorios entre 10 y 20:\n", num_rango)

#### **1.4.3.3 Distribución normal (Gaussiana)**

La distribución normal es una de las distribuciones más importantes en estadística. Genera números que tienden a agruparse alrededor de una media con una desviación estándar especificada.

In [ ]:
# Generar números con distribución normal (media=0, desviación estándar=1)
numeros_normales = # tu codigo aquí
print("10 números con distribución normal estándar:\n", numeros_normales)

# Generar números con distribución normal personalizada (media=100, desviación estándar=15)
numeros_normales_personalizados = # tu codigo aquí
print("\n10 números normales con media=100, desv est=15:\n", numeros_normales_personalizados)

#### **1.4.3.5 Reproducibilidad con semillas (Seeds)**

Las semillas permiten reproducir exactamente los mismos números "aleatorios" en ejecuciones posteriores. Esto es fundamental para la investigación científica y el debugging.

In [ ]:
print("=== Ejemplo 1: Usando semilla en NumPy ===")
# Primera ejecución con semilla
np.random.seed(123)
print("Primer set de números con seed=123:")
print(# tu codigo aquí)

print("\n=== Ejemplo 2: Usando semilla en random ===")
# Primera ejecución con semilla
rand.seed(999)
print("Primer set con seed=999:")
print([rand.randint(1, 100) for _ in range(5)])

#### **1.4.3.6 Otras distribuciones y operaciones avanzadas**

**NumPy** proporciona muchas otras distribuciones de probabilidad como Poisson, Binomial, Exponencial, etc.

In [ ]:
# Distribución Poisson (eventos que ocurren en intervalos de tiempo)
poisson = np.random.poisson(lam=3, size=10)
print("Números con distribución Poisson (λ=3):", poisson)

# Distribución Binomial (éxitos en n intentos)
binomial = np.random.binomial(n=10, p=0.5, size=10)
print("Números con distribución Binomial (n=10, p=0.5):", binomial)

# Distribución Exponencial (tiempo entre eventos)
exponencial = np.random.exponential(scale=2.0, size=10)
print("Números con distribución Exponencial (scale=2.0):", exponencial)

# Permutación aleatoria de un vector
vector = np.arange(10)  # [0,1,2,3,4,5,6,7,8,9]
permutacion = np.random.permutation(vector)
print("\nVector original:", vector)
print("Vector permutado:", permutacion)

# Muestreo aleatorio sin reemplazo
muestra = np.random.choice(np.arange(1, 50), size=5, replace=False)
print("\nMuestra de 5 números sin reemplazo del 1 al 49:", muestra)

### **1.4.4 Matrices**

In [ ]:
import numpy as np

# Creacion de matriz
matriz = # tu codigo aquí

matriz

* __Acceso a elementos por filas y columnas:__

In [ ]:
# Acceder al elemento en la primera fila, segunda columna
# tu codigo aquí

# Acceder al elemento en la tercera fila, primera columna
# tu codigo aquí

# Acceder a la segunda columna
# tu codigo aquí

# Acceder a la segunda fila
fila = # tu codigo aquí

Realizacemos algunas operaciones con matrices

In [ ]:
# Crear dos matrices
matriz1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

matriz2 = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])

# Suma de matrices (deben tener las mismas dimensiones)
suma = matriz1 + matriz2
print("Suma:\n", suma)

# Resta de matrices (deben tener las mismas dimensiones)
resta = matriz1 - matriz2
print("Resta:\n", resta)


# Multiplicación de elmento a elemento de matrices (deben tener las mismas dimensiones)
multiplicacion = matriz1 * matriz2
print("Multiplicación elemento por elemento:\n", multiplicacion)

# Multiplicación de matrices (producto matricial)

# El número de columnas de la matriz izquierda debe ser igual
# al número de filas de la matriz derecha
producto_matricial = np.dot(matriz1, matriz2)
print("Producto matricial:\n", producto_matricial)

# Transponer la matriz
transpuesta = matriz.T
print("Transposición:\n", transpuesta)

# Crear una matriz identidad de 3x3
identidad = np.eye(3)
print("Matriz identidad:\n", identidad)

# Calcular el determinante
np.linalg.det(matriz1)

### **1.4.5 Diccionarios**

In [ ]:
# Crear un diccionario vacío
mi_diccionario = {}

# Crear un diccionario con algunos pares clave-valor
estudiante = # tu codigo aquí

print(estudiante)

* __Acceso a un valor__:

In [ ]:
# Acceder al valor asociado con la clave "nombre"
nombre = # tu codigo aquí
print(nombre)

* __Modificar un valor__:

In [ ]:
# Cambiar el valor asociado con la clave "edad"
estudiante["edad"] = 22
print(estudiante)

* __Agregar un nuevo par clave-valor__:

In [ ]:
# Agregar una nueva clave "promedio" con su valor
estudiante["promedio"] = # tu codigo aquí
print(estudiante)

* __Eliminar un par clave-valor__:

In [ ]:
# Eliminar la clave "carrera" y su valor asociado
# tu codigo aquí
print(estudiante)

* __Recorrer un diccionario__:

In [ ]:
# Recorrer las claves y valores de un diccionario
for clave, valor in estudiante.items():
    print(f"{clave}: {valor}")

## **1.5 Introducción a la manipulación de datos: Creación, manipulación y análisis de datos tabulares**

In [1]:
# Crear un diccionario
data={
    "Nombre":["María","Ana", "Pedro", "Juan", "Carlos", "Sara"], # Lista de nombres se plantea con corchetes
    "Edad":[21,22,19,26,22,19], # Lista de edades se plantea con corchetes
    "Género":["F","F","M","M","M","F"] # Lista de género se plantea con corchetes
}

# Imprimir data
print(data)

{'Nombre': ['María', 'Ana', 'Pedro', 'Juan', 'Carlos', 'Sara'], 'Edad': [21, 22, 19, 26, 22, 19], 'Género': ['F', 'F', 'M', 'M', 'M', 'F']}

2. Importemos el módulo __pandas__:

In [2]:
# Libreria 
import pandas as pd

3. Convertimos el diccionario en un __DataFrame__:

In [3]:
# DataFrame es una función que está dentro del módulo pandas
df=pd.DataFrame(data)
df

   Nombre  Edad Género
0   María    21      F
1     Ana    22      F
2   Pedro    19      M
3    Juan    26      M
4  Carlos    22      M
5    Sara    19      F

### **1.5.2 Manipulación de datos**

In [4]:
# Obtener información sobre la estructura del DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Nombre  6 non-null      object
 1   Edad    6 non-null      int64
 2   Género  6 non-null      object
dtypes: int64(1), object(2)
memory usage: 272.0+ bytes

In [5]:
# Obtener las dimensiones del DataFrame
df.shape

(6, 3)

In [6]:
# Mostrar las 5 primeras filas del DataFrame
df.head()

# Mostrar las 2 primeras filas del DataFrame
df.head(2)

  Nombre  Edad Género
0  María    21      F
1    Ana    22      F

In [7]:
# Mostrar las 5 ultimas filas de DataFrame
df.tail()

# Mostrar las 3 ultimas filas de DataFrame
df.tail(3)

   Nombre  Edad Género
3    Juan    26      M
4  Carlos    22      M
5    Sara    19      F

In [8]:
df.columns

Index(['Nombre', 'Edad', 'Género'], dtype='object')

In [9]:
# Renombrar las columnas del DataFrame
df.columns = ['Nombre_Cliente', 'Edad_Cliente', 'Genero_Cliente']

In [11]:
# Obtener el índice del DataFrame
df.columns

Index(['Nombre_Cliente', 'Edad_Cliente', 'Genero_Cliente'], dtype='object')

In [32]:
df.index = ['a', 'b', 'c', 'd', 'e', 'f']
df.index

Index(['a', 'b', 'c', 'd', 'e', 'f'], dtype='object')

In [15]:
df.head()

    Nombre_Cliente  Edad_Cliente Genero_Cliente
ID1          María            21              F
ID2            Ana            22              F
ID3          Pedro            19              M
ID4           Juan            26              M
ID5         Carlos            22              M

In [16]:
# Ordenar el DataFrame df por la columna 'Edad' en orden descendente
df.sort_values(by='Edad_Cliente', ascending=False)

    Nombre_Cliente  Edad_Cliente Genero_Cliente
ID4           Juan            26              M
ID2            Ana            22              F
ID5         Carlos            22              M
ID1          María            21              F
ID3          Pedro            19              M
ID6           Sara            19              F

In [27]:
# Seleccionar la primera fila (índice 0)
df.iloc[0]

# Seleccionar las primeras tres filas
df.iloc[0:3]

# Seleccionar el valor en la primera fila y segunda columna
df.iloc[0, 1]

# Seleccionar las primeras dos filas y las primeras tres columnas
df.iloc[0:2, 0:3]

# Seleccionar todos los valores de la segunda columna
df.iloc[:,1]

# Seleccionar las últimas dos filas de todas las columnas
df.iloc[-2:]

# Seleccionar las columnas por su nombre 
df['Nombre_Cliente']

# Otra forma de seleccionar las columnas por su nombre 
df.Nombre_Cliente

# Seleccionar el valor en la primera fila como un DataFrame
df.iloc[[0],:]

# Seleccionar las filas 1 y 3 como un DataFrame
df.iloc[[1,3],:]

# Seleccionar las columnas 1 y 3 como un DataFrame
df.iloc[:,[0,2]]

    Nombre_Cliente Genero_Cliente
ID1          María              F
ID2            Ana              F
ID3          Pedro              M
ID4           Juan              M
ID5         Carlos              M
ID6           Sara              F

Este método es clave para acceder y manipular datos en un DataFrame utilizando posiciones, especialmente cuando los índices o nombres de columnas no son intuitivos o cuando estás realizando operaciones sobre DataFrames grandes y complejos.

* El método `df.loc` en Pandas se utiliza para acceder a un DataFrame por etiquetas de filas y columnas, a diferencia de `iloc`, que usa posiciones numéricas. `loc` permite una variedad de operaciones para seleccionar y filtrar datos basados en las etiquetas de los índices y columnas. Por ejemplo:

In [37]:
# Seleccionar la fila con la etiqueta 'b'
df.loc['b']

# Seleccionar las filas con etiquetas de 'a' a 'c' (inclusive)
df.loc['a':'c']

# Seleccionar el valor en la fila con etiqueta 'b' y columna 'Edad'
df.loc['b', 'Edad_Cliente']

# Seleccionar las filas 'a' a 'c' y las columnas 'Nombre' y 'Edad'
df.loc['a':'c', ['Nombre_Cliente', 'Edad_Cliente']]

# Seleccionar todas las filas y solo la columna 'Genero'
df.loc[:, 'Genero_Cliente']

# Seleccionar todas las filas donde 'Edad' es mayor que 25
df.loc[df['Edad_Cliente'] > 25]

  Nombre_Cliente  Edad_Cliente Genero_Cliente
d           Juan            26              M

:::{admonition} **Ejercicio 3**
:class: tip

Se recolectaron datos de 8 estudiantes universitarios y se resumieron en la siguiente tabla:

<div align="center">

|MASA| ESTATURA| GENERO| ESTRATO |FUMA|
|----|---------|--------|--------|----|
|71 |183| HOMBRE |2| NO|
|45| 168 |HOMBRE| 1 |NO|
|50| 164 |HOMBRE| 1 |NO|
|60| 164 |MUJER |3 |SI|
|61| 167 |HOMBRE| 3| SI|
|84| 182 |HOMBRE| 3| NO|
|55| 168 |MUJER |3 |NO|
|60| 170 |HOMBRE| 3 |SI|

</div>

1. Crear un data frame y llamarlo __df__.
2. Realizar un análisis descriptivo básico de todas las variables.
3. Extraer un subconjunto de datos con los primeros 4 estudiantes y llamarlo __subc1__.
4. Extraer las variables categóricas y guardarlas en un subconjunto llamado __subc2__
5. Extraer las variables numéricas y guardarlas en un subconjunto llamado __subc3__

:::

## **1.6 Importación de datos**

Ahora importemos un archivo plano con `Pandas`:

In [38]:
import pandas as pd

# Importar un archivo CSV como DataFrame
filename = r'_data\datadescrip\Wine.csv'
data = pd.read_csv(filename)

# Ver las primeras 5 filas del DataFrame
data.head()

,Alcohol,Malic_Acid,Ash,Ash_Alcanity,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280,Proline,Customer_Segment
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,1
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050,1
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,1
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480,1
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,1

In [39]:
data_array = data.to_numpy()
data_array

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 3.920e+00, 1.065e+03,
        1.000e+00],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 3.400e+00, 1.050e+03,
        1.000e+00],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 3.170e+00, 1.185e+03,
        1.000e+00],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 1.560e+00, 8.350e+02,
        3.000e+00],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 1.620e+00, 8.400e+02,
        3.000e+00],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 1.600e+00, 5.600e+02,
        3.000e+00]])

In [41]:
# Crear un DataFrame
data = {
    'Columna1': [1, 4, 7],
    'Columna2': [2, 5, 8],
    'Columna3': [3, 6, 9]
}
df = pd.DataFrame(data)

# Guardar el DataFrame en un archivo CSV
df.to_csv('_data/datamanip/comercial.csv', index=True)

### **1.6.2. Importación y exportación de datos serializados**

In [42]:
import pickle

with open('_data/datamanip/data_fruta.pkl','rb') as file:
    data = pickle.load(file)
    
print(data)

{'apple': 10, 'banana': 20, 'cherry': 30}

In [45]:
# Crear un objeto (por ejemplo, un diccionario)
data = {'a': 1, 'b': 2, 'c': 3}

# Guardar el objeto en un archivo pickle
with open('_data/datamanip/archivo_2.pkl', 'wb') as file:
    pickle.dump(data, file)

### **1.6.3. Importación y exportación de datos en Excel**

Debemos instalar en el terminal con el environment activo, la siguiente instrucción `pip install openpyxl`

In [ ]:
# Lee la hoja '1960–1966' del archivo Excel y la carga en un DataFrame
df = pd.read_excel(r'_data\datamanip\urbanpop.xlsx',
                   sheet_name='1960–1966')
df.info()

O si prefieres usar el índice de la hoja:

In [ ]:
# Lee la primera hoja (índice 0) del archivo Excel
df = d.read_excel(r'_data\datamanip\urbanpop.xlsx',
                   sheet_name=0)

In [ ]:
# Lee las hojas '1960–1966' y '1975–2011' del archivo Excel
sheets = pd.read_excel('_data/datamanip/urbanpop.xlsx',
                       sheet_name=['1960-1966',
                                   '1975-2011'])

# Accede a cada DataFrame por el nombre de la hoja
df1 = sheets['1960-1966']
df2 = sheets['1975-2011']

In [57]:
df_total = pd.concat([df1, df2], ignore_index=True)

In [59]:
df_total.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 45 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   country  418 non-null    object
 1   1960     198 non-null    float64
 2   1961     209 non-null    float64
 3   1962     209 non-null    float64
 4   1963     209 non-null    float64
 5   1964     209 non-null    float64
 6   1965     209 non-null    float64
 7   1966     209 non-null    float64
 8   1975     209 non-null    float64
 9   1976     209 non-null    float64
 10  1977     209 non-null    float64
 11  1978     209 non-null    float64
 12  1979     209 non-null    float64
 13  1980     209 non-null    float64
 14  1981     209 non-null    float64
 15  1982     209 non-null    float64
 16  1983     209 non-null    float64
 17  1984     209 non-null    float64
 18  1985     209 non-null    float64
 19  1986     209 non-null    float64
 20  1987     209 non-null    float64
 21  1988     209 non-null    float64
 22  1989     209 non-null    float64
 23  1990     209 non-null    float64
 24  1991     209 non-null    float64
 25  1992     208 non-null    float64
 26  1993     208 non-null    float64
 27  1994     208 non-null    float64
 28  1995     209 non-null    float64
 29  1996     209 non-null    float64
 30  1997     209 non-null    float64
 31  1998     209 non-null    float64
 32  1999     209 non-null    float64
 33  2000     209 non-null    float64
 34  2001     209 non-null    float64
 35  2002     209 non-null    float64
 36  2003     209 non-null    float64
 37  2004     209 non-null    float64
 38  2005     209 non-null    float64
 39  2006     209 non-null    float64
 40  2007     209 non-null    float64
 41  2008     209 non-null    float64
 42  2009     209 non-null    float64
 43  2010     209 non-null    float64
 44  2011     209 non-null    float64
dtypes: float64(44), object(1)
memory usage: 147.1+ KB

In [56]:
# Crear un DataFrame
data = {
    'Columna1': [1, 4, 7],
    'Columna2': [2, 5, 8],
    'Columna3': [3, 6, 9]
}
df = pd.DataFrame(data)

# Guardar el DataFrame en un archivo Excel
df.to_excel('_data/datamanip/archivo_nuevo.xlsx', index=False)

## **1.7. Manipulación de datos con pandas**

La librería `pandas` (cuyo nombre deriva de *panel data*, un término utilizado para describir conjuntos de datos estructurados y multidimensionales) ofrece potentes estructuras de datos y funciones de alto nivel que facilitan el trabajo con datos estructurados de manera eficiente y cómoda. Es una herramienta esencial en el análisis de datos, ampliamente utilizada por su versatilidad y funcionalidad.

   ```{figure} /_image/pandas.png
   :align: center
   :name: Imagen de pandas
   :scale: 50
   ```

Entre los principales objetos que proporciona pandas se encuentran el `DataFrame`, una estructura tabular bidimensional, la `Serie`, ambos construidos sobre arrays multidimensionales de `NumPy` y el `Panel`, que representa un cubo de datos tridimensional. Aunque `NumPy` es excelente para el almacenamiento eficiente de datos con su estructura `ndarray, presenta ciertas limitaciones en análisis más complejos. Estas limitaciones incluyen la falta de flexibilidad para aplicar etiquetas a los datos, gestionar valores faltantes, realizar agrupaciones, entre otros. Pandas supera estas barreras con sus estructuras de datos avanzadas, proporcionando una mayor flexibilidad y funcionalidad.

Para más información, puedes consultar la [documentación oficial de pandas](https://pandas.pydata.org/), donde encontrarás recursos y ejemplos detallados para aprovechar al máximo esta poderosa librería.

**Recordemos algunas cosas de `pandas`**

Para iniciar el proceso de creación, manipulación, entre otras debemos instalar el ia en el terminal. **Recuerde activar el ambiente**.

![installpandas](_image/installpandas.png)

Importemos la libreria `numpy` y `pandas`

In [1]:
import pandas as pd
import numpy as np

Carguemos el conjunto de datos de **marketing del banco** `bank-full`. 

Los datos están relacionados con `campañas de marketing directo` (llamadas telefónicas) de una institución bancaria portuguesa.

Este conjunto de datos tiene 4521 observaciones y 17 variables. Las variables son:

* **age:** Edad del cliente.
* **job**: Profesión del cliente (por ejemplo, desempleado, servicios, gestión).
* **marital**: Estado civil del cliente (soltero, casado, divorciado).
* **education**: Nivel educativo del cliente (primaria, secundaria, terciaria).
* **default** : Indica si el cliente tiene crédito en incumplimiento (sí o no).
* **balance**: Saldo promedio anual de la cuenta bancaria del cliente.
* **housing**: Indica si el cliente tiene un préstamo hipotecario (sí o no).
* **loan**: Indica si el cliente tiene un préstamo personal (sí o no).
* **contact**: Tipo de comunicación de contacto (teléfono celular, teléfono fijo).
* **day**: Día del mes en que se realizó el último contacto con el cliente.
* **month**: Mes en que se realizó el último contacto con el cliente.
* **duration**: Duración del último contacto en segundos.
* **campaign**: Número de contactos realizados durante esta campaña de marketing.
* **pdays**: Días que han pasado desde que el cliente fue contactado por última vez en una campaña anterior (valores -1 indican que el cliente no fue contactado previamente).
* **previous**: Número de contactos realizados antes de esta campaña.
* **poutcome**: Resultado de una campaña de marketing anterior (éxito, fracaso, desconocido).
* **y**: Resultado de la campaña actual (si el cliente suscribió o no un depósito a plazo fijo).

In [6]:
# Asignar la URL del archivo: url
url ='https://raw.githubusercontent.com/cdeoroaguado/Datos/refs/heads/main/datamanip/bank/bank-full.csv'

# leer el archivo en u dataframe:df
df = pd.read_csv(url,sep=';')

# Imprimir el encabezado del dataframe
df.head()

# Mostrar las 5 ultimas filas de DataFrame
df.tail()

# Concatenar el encabezado y las últimas 5 filas del DataFrame
result = pd.concat([df.head(), df.tail()])
print(result)

       age           job   marital  education default  balance housing loan  \
0       58    management   married   tertiary      no     2143     yes   no
1       44    technician    single  secondary      no       29     yes   no
2       33  entrepreneur   married  secondary      no        2     yes  yes
3       47   blue-collar   married    unknown      no     1506     yes   no
4       33       unknown    single    unknown      no        1      no   no
45206   51    technician   married   tertiary      no      825      no   no
45207   71       retired  divorced    primary      no     1729      no   no
45208   72       retired   married  secondary      no     5715      no   no
45209   57   blue-collar   married  secondary      no      668      no   no
45210   37  entrepreneur   married  secondary      no     2971      no   no

         contact  day month  duration  campaign  pdays  previous poutcome    y
0        unknown    5   may       261         1     -1         0  unknown   no
1        unknown    5   may       151         1     -1         0  unknown   no
2        unknown    5   may        76         1     -1         0  unknown   no
3        unknown    5   may        92         1     -1         0  unknown   no
4        unknown    5   may       198         1     -1         0  unknown   no
45206   cellular   17   nov       977         3     -1         0  unknown  yes
45207   cellular   17   nov       456         2     -1         0  unknown  yes
45208   cellular   17   nov      1127         5    184         3  success  yes
45209  telephone   17   nov       508         4     -1         0  unknown   no
45210   cellular   17   nov       361         2    188        11    other   no

Las dimensiones del dataset:

In [7]:
# Obtener las dimensiones del DataFrame
df.shape

(45211, 17)

Información de la estructura del dataset de marketing:

In [8]:
# Obtener información sobre la estructura del DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64
 12  campaign   45211 non-null  int64
 13  pdays      45211 non-null  int64
 14  previous   45211 non-null  int64
 15  poutcome   45211 non-null  object
 16  y          45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB

El atributo `df.size` en pandas devuelve el número total de elementos en un `DataFrame`. Esto se calcula multiplicando el número de filas por el número de columnas. Es útil para obtener una visión rápida del tamaño total del DataFrame en términos de elementos.

In [9]:
# número total de elementos en el dataframe
df.size

768587

Puede ocurrir que el conjunto de datos de marketing para la banca tenga duplicados. El método `drop_duplicates()` en pandas se utiliza para eliminar filas duplicadas de un DataFrame. Este método permite identificar y remover filas que contienen los mismos valores en las columnas seleccionadas, o en todas las columnas si no se especifica ninguna.

In [10]:
# Eliminar filas duplicadas
df = df.drop_duplicates()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64
 12  campaign   45211 non-null  int64
 13  pdays      45211 non-null  int64
 14  previous   45211 non-null  int64
 15  poutcome   45211 non-null  object
 16  y          45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB

Ahora, el nombres de las variables, el indice, el tipo de dato del dataset de marketing

In [12]:
# nombre de las variables
df.columns

# Obtener el índice del DataFrame
df.index

# tipo de dato
# tu codigo aquí

RangeIndex(start=0, stop=45211, step=1)

Queremos saber los clientes menores de 20 años:

In [14]:
# Seleccionar solo las filas donde la condición es True
df.loc[df['age'] < 20]

# Mostrar los clientes menores de 20 años
dfm20 = df.loc[df['age'] < 20]

# imprimir el dataframe las 5 primeras
dfm20.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
30791,19,student,single,unknown,no,1169,no,no,cellular,6,feb,463,18,-1,0,unknown,no
31041,19,student,single,unknown,no,0,no,no,cellular,11,feb,123,3,-1,0,unknown,no
31263,19,student,single,unknown,no,27,no,no,telephone,5,mar,86,12,-1,0,unknown,no
31304,19,student,single,secondary,no,1803,no,no,cellular,10,mar,59,1,-1,0,unknown,no
31432,19,student,single,primary,no,134,no,no,cellular,27,mar,271,2,-1,0,unknown,yes

Escojamos las columnas `age`, `marital`, `balance`, `y` de los clientes menores de 20

In [15]:
# seleccionemos las columnas
new_dfm20 = dfm20[['age','marital','balance','y']]

# imprimir
print(new_dfm20.head())

       age marital  balance    y
30791   19  single     1169   no
31041   19  single        0   no
31263   19  single       27   no
31304   19  single     1803   no
31432   19  single      134  yes

In [ ]:
# ordenar
new_dfm20.sort_values(by='balance', ascending=False)

Puedes aplicar una función personalizada a una columna específica del DataFrame usando el método `apply()` de `pandas`. Supongamos que deseas crear una nueva columna llamada `balance_category` que clasifique el balance de cada cliente en `"Bajo"`, `"Medio"` o `"Alto"` según ciertos umbrales.

In [18]:
# Definir una función para categorizar el balance
def categorizar_balance(balance):
    if balance < 500:
        return 'Bajo'
    elif 500 <= balance < 1500:
        return 'Medio'
    else:
        return 'Alto'

In [20]:
# Aplicar la función 'categorizar_balance' a la columna 'balance'
# y crear la nueva columna 'balance_category'
new_dfm20.loc[:,'balance_category'] = new_dfm20['balance'].apply(categorizar_balance)

# Mostrar el DataFrame actualizado
print(new_dfm20.head())

       age marital  balance    y balance_category
30791   19  single     1169   no            Medio
31041   19  single        0   no             Bajo
31263   19  single       27   no             Bajo
31304   19  single     1803   no             Alto
31432   19  single      134  yes             Bajo

Ahora, debemos obtener los clientes menores de 20 que si se suscribieron. Ademas los que se suscribieron con balance bajo.

In [21]:
new_dfm20['y'].unique()

array(['no', 'yes'], dtype=object)

In [22]:
# menores de 20 que se suscribieron
new_dfm20.loc[new_dfm20['y'] == 'yes']

# Otra forma de seleccionarlos
new_dfm20[new_dfm20['y'].isin(['yes'])]

# menores de 20 que se suscribieron con balance bajo
new_dfm20[(new_dfm20['y'] == 'yes') & (new_dfm20['balance_category'] == 'Bajo')]

       age marital  balance    y balance_category
31432   19  single      134  yes             Bajo
40564   19  single      103  yes             Bajo
40744   18  single      108  yes             Bajo
41273   18  single        3  yes             Bajo
41487   18  single      108  yes             Bajo
41930   19  single      329  yes             Bajo
42954   18  single      108  yes             Bajo
43258   19  single      108  yes             Bajo
43408   19  single      394  yes             Bajo
43594   19  single      329  yes             Bajo
43637   18  single      348  yes             Bajo
44110   19  single      372  yes             Bajo
44211   19  single      302  yes             Bajo
44493   19  single      108  yes             Bajo

#### **Adición de nuevas columnas al DataFrame**

In [23]:
new_dfm20.loc[:,'balance_por_age'] = new_dfm20['balance'] / new_dfm20['age']
print(new_dfm20.head())

       age marital  balance    y balance_category  balance_por_age
30791   19  single     1169   no            Medio        61.526316
31041   19  single        0   no             Bajo         0.000000
31263   19  single       27   no             Bajo         1.421053
31304   19  single     1803   no             Alto        94.894737
31432   19  single      134  yes             Bajo         7.052632

C:\Users\cdeor\AppData\Local\Temp\ipykernel_2756\3820989179.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_dfm20.loc[:,'balance_por_age'] = new_dfm20['balance'] / new_dfm20['age']

* Ahora, veremos la adición condicional de columnas. Vamos a intentar añadir una columna basada en el valor de la edad, digamos que todo lo que sea más de 17 como mayor de edad (codificado como 1) y todo lo que sea inferior a 17 como menor de edad (codificado como 0).

In [ ]:
new_dfm20.loc[:,'age_cat'] = # tu codigo aquí
print(new_dfm20.tail())

#### **Indices explicitos**

Analicemos algunas funciones utiles de la indexación explicita:

* `df.set_index()`; Este método se usa para establecer una o más columnas del DataFrame como su índice.

In [ ]:
# Establecer la columna 'job' como índice
# tu codigo aquí

* `df.reset_index()`:Este método se usa para restablecer el índice del DataFrame, devolviendo los índices actuales a columnas y creando un nuevo índice numérico predeterminado. Si usas el parámetro `drop=True` indica que se debe eliminar la columna de índice original en lugar de moverla a una columna.

In [ ]:
# tu codigo aquí

* `df.sort_index()`: Este método ordena las filas del DataFrame en función del índice.

In [ ]:
# orden de los indices
# tu codigo aquí

En conclusión, el uso de índices explícitos en Python es una técnica poderosa que permite un control detallado sobre la manipulación de datos. Ya sea en estructuras simples como listas o en análisis más complejos utilizando pandas, el conocimiento y uso adecuado de índices explícitos puede mejorar significativamente la eficiencia y claridad de tu código.